[package]
name = "hangfire-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# internal
fnf-rs = { path = "../fnf-rs/" }
fnf-derive = { path = "../fnf-derive" }

# external
rocket = { version = "0.5.0-rc.2", features = ["secrets", "tls", "json"] }
anyhow = "1.0.58"
uuid = { version = "1.1.2", features = ["v4"] }
serde = "1.0"
