name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: pustovitDmytro/redis-github-action@v1.0.2
    - uses: Namoshek/rabbitmq-github-action@v1.1.0
    - name: Run tests
      run: cargo test -- --test-threads 1 --nocapture
